sudo: required
before_install:
  - sudo apt-get install build-essential
  - pip install --user pyyaml cpp-coveralls

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - g++

# Build steps
script:
  - mkdir build
  - cd build
  - ../deps/cmake/bin/cmake .. -DCMAKE_BUILD_TYPE=COVERAGE
  - make test_HODLR
  - ./test/test_HODLR
  - cd ${TRAVIS_BUILD_DIR}

after_success:
  - coveralls -i src
